In [1]:
import pandas as pd

students = pd.read_csv("../data/students.csv")
dt_scores = pd.read_csv("../data/dt_scores.csv")

In [4]:
print("===== students.head() =====")
print(students.head())

print("\n")

print("===== dt_scores.head() =====")
print(dt_scores.head())

print("\n")

print("===== students.info() =====")
students.info()

print("\n")

print("===== dt_scores.info() =====")
dt_scores.info()

===== students.head() =====
  student_id name age class
0    4MR_001  김민준  초4   4MR
1    4MR_002  박서준  초4   4MR
2    4MR_003  이도윤  초4   4MR
3    4MR_004  최지호  초4   4MR
4    4MR_005  한예린  초4   4MR


===== dt_scores.head() =====
  student_id        date dt_type  score
0    4MR_001  2026-07-01      현행     78
1    4MR_001  2026-07-01      선행     73
2    4MR_001  2026-07-02      현행     81
3    4MR_001  2026-07-02      선행     77
4    4MR_001  2026-07-03      현행     84


===== students.info() =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  20 non-null     object
 1   name        20 non-null     object
 2   age         20 non-null     object
 3   class       20 non-null     object
dtypes: object(4)
memory usage: 768.0+ bytes


===== dt_scores.info() =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  1200 non-null   object
 1   date        1200 non-null   object
 2   dt_type     1200 non-null   object
 3   score       1200 non-null   int64
dtypes: int64(1), object(3)
memory usage: 37.6+ KB

In [5]:
df = pd.merge(
    dt_scores,
    students,
    on="student_id"
)

In [6]:
df.head()

  student_id        date dt_type  score name age class
0    4MR_001  2026-07-01      현행     78  김민준  초4   4MR
1    4MR_001  2026-07-01      선행     73  김민준  초4   4MR
2    4MR_001  2026-07-02      현행     81  김민준  초4   4MR
3    4MR_001  2026-07-02      선행     77  김민준  초4   4MR
4    4MR_001  2026-07-03      현행     84  김민준  초4   4MR

In [7]:
df.groupby("name")["score"].mean()

name
강하준    76.833333
김민준    78.066667
김서윤    90.500000
박도윤    81.816667
박서준    81.683333
송예준    82.283333
신도현    83.866667
오지훈    75.300000
유시우    81.033333
윤지안    93.066667
이도윤    76.216667
이하린    75.616667
임도현    83.316667
장예은    91.316667
정서준    70.350000
정유진    82.416667
조하은    79.133333
최민재    79.800000
최지호    77.766667
한예린    78.200000
Name: score, dtype: float64

In [8]:
df.groupby("class")["score"].mean()

class
4MR     78.386667
6MR1    81.280000
7MS1    82.030000
7MS2    82.020000
Name: score, dtype: float64

In [9]:
df.groupby("dt_type")["score"].mean()

dt_type
선행    79.081667
현행    82.776667
Name: score, dtype: float64

In [10]:
df = pd.merge(
    dt_scores,
    students,
    on="student_id",
    how="left"
)

print("=" * 60)
print("Merge Result")
print("=" * 60)

df.head()

============================================================
Merge Result
============================================================

  student_id        date dt_type  score name age class
0    4MR_001  2026-07-01      현행     78  김민준  초4   4MR
1    4MR_001  2026-07-01      선행     73  김민준  초4   4MR
2    4MR_001  2026-07-02      현행     81  김민준  초4   4MR
3    4MR_001  2026-07-02      선행     77  김민준  초4   4MR
4    4MR_001  2026-07-03      현행     84  김민준  초4   4MR

In [17]:
df.shape

(1200, 7)

In [16]:
df.columns

Index(['student_id', 'date', 'dt_type', 'score', 'name', 'age', 'class'], dtype='object')

In [18]:
print("=" * 60)
print("기초 통계")
print("=" * 60)

print(df.describe())

============================================================
기초 통계
============================================================
             score
count  1200.000000
mean     80.929167
std       7.420132
min      58.000000
25%      76.000000
50%      80.000000
75%      86.000000
max     100.000000

In [19]:
print("=" * 60)
print("DT 점수 기초 통계")
print("=" * 60)

print(df["score"].describe())

============================================================
DT 점수 기초 통계
============================================================
count    1200.000000
mean       80.929167
std         7.420132
min        58.000000
25%        76.000000
50%        80.000000
75%        86.000000
max       100.000000
Name: score, dtype: float64